services:
  avnav:
    image: avnav-halos:20251028
    container_name: avnav
    restart: unless-stopped
    environment:
      TZ: Europe/Copenhagen
    volumes:
      - avnav-data:/var/lib/avnav
      - avnav-user:/home/user
    networks:
      - avnav-internal
      - halos-proxy-network
    labels:
      - traefik.enable=true
      - traefik.docker.network=halos-proxy-network
      - traefik.http.routers.app-4432.rule=Host(`avnav.example.invalid`)
      - traefik.http.routers.app-4432.entrypoints=websecure
      - traefik.http.routers.app-4432.tls=true
      - traefik.http.services.app-4432.loadbalancer.server.port=8083

volumes:
  avnav-data:
  avnav-user:

networks:
  avnav-internal:
  halos-proxy-network:
    external: true
